version: '3.5'

services:
  ui:
    build: ./task-ui-react
    volumes:
      - ./task-ui-react:/usr/src
      - /app/node_modules
    ports:
      - '${UI_PORT}:${UI_PORT}'
    command: npm run ${UI_COMMAND}
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    depends_on:
      - postgres
    build: ./task-api
    volumes:
      - ./task-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
    command: npm run ${API_COMMAND}
    networks:
      - app-network
    environment:
      UI_URL: ${UI_URL}:${UI_PORT}
      API_PORT: ${API_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
